Repository 1910-Hiry-Team/CarBnb, pull requests merged in 2025-01, with the labels that each got.

#5 Add User authentication and add Devise gem compatibility
  Gemfile
  Gemfile.lock
  app/assets/images/logo.png
  app/controllers/application_controller.rb
  app/controllers/pages_controller.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_flashes.html.erb
  app/views/shared/_navbar.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20250121114229_devise_create_users.rb
  db/migrate/20250121133434_add_first_and_last_name_to_users.rb
  db/schema.rb
  test/models/user_test.rb
Labels: enhancement

#6 Implement the Car model
  Gemfile
  Gemfile.lock
  app/controllers/cars_controller.rb
  app/controllers/users_controller.rb
  app/helpers/cars_helper.rb
  app/models/car.rb
  app/views/cars/create.html.erb
  app/views/cars/destroy.html.erb
  app/views/cars/edit.html.erb
  app/views/cars/index.html.erb
  app/views/cars/new.html.erb
  app/views/cars/show.html.erb
  app/views/cars/update.html.erb
  config/routes.rb
  db/migrate/20250121140102_create_cars.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/cars_controller_test.rb
  test/controllers/users_controller_test.rb
  test/models/car_test.rb
Labels: enhancement

#17 Implement a "view all cars" view
  app/assets/stylesheets/application.scss
  app/controllers/cars_controller.rb
  app/views/cars/index.html.erb
Labels: enhancement, frontend, backend, DO NOT MERGE

#19 resolve bugs linked to search and index
  app/controllers/cars_controller.rb
  app/views/cars/index.html.erb
Labels: bug

#22 Fix car_id/cars_id mismatch
  db/migrate/20250122163618_rename_cars_id_to_car_id_in_bookings.rb
  db/schema.rb
  db/seeds.rb
Labels: bug

#24 Fix btns in index
  app/views/cars/index.html.erb
Labels: frontend, restructuring

#9 Seeding and validations
  app/models/user.rb
  db/seeds.rb
Labels: enhancement, help wanted

#34 Nico create booking
  app/controllers/bookings_controller.rb
  app/views/bookings/new.html.erb
  config/routes.rb
  db/schema.rb
Labels: backend

#38 Create booking
  app/controllers/bookings_controller.rb
  app/views/bookings/edit.html.erb
  app/views/bookings/index.html.erb
  app/views/bookings/new.html.erb
  app/views/bookings/show.html.erb
Labels: frontend, backend

#41 Corrected the edit and update
  app/controllers/bookings_controller.rb
  app/views/bookings/edit.html.erb
Labels: bug, backend

#33 Misc fixes
  app/controllers/application_controller.rb
  app/views/bookings/new.html.erb
  app/views/cars/index.html.erb
  app/views/cars/show.html.erb
  db/schema.rb
Labels: bug, frontend, backend

#40 add destroy booking
  app/controllers/bookings_controller.rb
  app/views/bookings/index.html.erb
  app/views/bookings/show.html.erb
Labels: frontend, backend

#42 Back link edit is working now
  app/views/bookings/edit.html.erb
  db/schema.rb
Labels: bug, backend

#46 Pundit, New/Create Car, Edit/Update car, Destroy car
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/bookings_controller.rb
  app/controllers/cars_controller.rb
  app/controllers/pages_controller.rb
  app/controllers/users_controller.rb
  app/policies/application_policy.rb
  app/policies/booking_policy.rb
  app/policies/car_policy.rb
  app/policies/devise_policy.rb
  app/policies/user_policy.rb
  app/views/cars/_create_form.html.erb
  app/views/cars/_edit_form.html.erb
  app/views/cars/edit.html.erb
  app/views/cars/index.html.erb
  app/views/cars/new.html.erb
  app/views/cars/show.html.erb
  app/views/shared/_navbar.html.erb
  config/environments/development.rb
  test/policies/booking_policy_test.rb
  test/policies/car_policy_test.rb
  test/policies/devise_policy_test.rb
  test/policies/user_policy_test.rb
Labels: enhancement, backend, DO NOT MERGE

#49 add-flatpickr
  app/controllers/bookings_controller.rb
  app/javascript/controllers/datepicker_controller.js
  app/views/bookings/edit.html.erb
  app/views/bookings/new.html.erb
  app/views/layouts/application.html.erb
  bin/importmap
  config/importmap.rb
  vendor/javascript/flatpickr.js
Labels: frontend, backend

#50 Misc Bug fixes & improvements
  app/views/bookings/index.html.erb
  app/views/bookings/new.html.erb
  app/views/bookings/show.html.erb
  app/views/cars/index.html.erb
  app/views/cars/show.html.erb
  db/seeds.rb
Labels: bug, restructuring
